version: "3.7"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      GITHUB_COM_TOKEN: ${GITHUB_COM_TOKEN}
      GOPRIVATE: "github.com/litencatt/uniar"
      UNIAR_DSN: mysql://root@db:3306/unisonair?parseTime=true&loc=Asia%2FTokyo
  # db:
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_USER: "app"
  #     MYSQL_PASSWORD: "app"
  #     MYSQL_DATABASE: "unisonair"
  #     TZ: "Asia/Tokyo"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./database/sql:/docker-entrypoint-initdb.d
