version: "3.7"
services:
  app:
    build:
      context: .
    ports:
      - "8090:8090"      
    volumes:
      - .:/app
  # db:
  #   image: mysql:8
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #     MYSQL_USER: "app"
  #     MYSQL_PASSWORD: "app"
  #     MYSQL_DATABASE: "unisonair"
  #     TZ: "Asia/Tokyo"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./database/sql:/docker-entrypoint-initdb.d
