// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: color_type.sql

package repository

import (
	"context"
)

const getColorTypeList = `-- name: GetColorTypeList :many
SELECT id, name FROM color_types ORDER BY id
`

type GetColorTypeListRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetColorTypeList(ctx context.Context, db DBTX) ([]GetColorTypeListRow, error) {
	rows, err := db.QueryContext(ctx, getColorTypeList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetColorTypeListRow
	for rows.Next() {
		var i GetColorTypeListRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
