// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: live.sql

package repository

import (
	"context"
)

const registLive = `-- name: RegistLive :exec
INSERT INTO lives (name, group_id) VALUES (?, ?)
`

type RegistLiveParams struct {
	Name    string
	GroupID int32
}

func (q *Queries) RegistLive(ctx context.Context, db DBTX, arg RegistLiveParams) error {
	_, err := db.ExecContext(ctx, registLive, arg.Name, arg.GroupID)
	return err
}
