// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: member.sql

package repository

import (
	"context"
)

const getMemberList = `-- name: GetMemberList :many
SELECT id, name FROM members WHERE group_id = ?
`

type GetMemberListRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetMemberList(ctx context.Context, db DBTX, groupID int32) ([]GetMemberListRow, error) {
	rows, err := db.QueryContext(ctx, getMemberList, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMemberListRow
	for rows.Next() {
		var i GetMemberListRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembers = `-- name: GetMembers :many
SELECT
	g. ` + "`" + `name` + "`" + ` AS ` + "`" + `group` + "`" + `,
	m. ` + "`" + `name` + "`" + `,
	m.phase,
	m.graduated
FROM
	members m
	JOIN ` + "`" + `groups` + "`" + ` g ON m.group_id = g.id
ORDER BY
	g.id, m.phase, m.first_name asc
`

type GetMembersRow struct {
	Group     string
	Name      string
	Phase     int32
	Graduated bool
}

func (q *Queries) GetMembers(ctx context.Context, db DBTX) ([]GetMembersRow, error) {
	rows, err := db.QueryContext(ctx, getMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersRow
	for rows.Next() {
		var i GetMembersRow
		if err := rows.Scan(
			&i.Group,
			&i.Name,
			&i.Phase,
			&i.Graduated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
