// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"database/sql"
	"time"
)

type CenterSkill struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type ColorType struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type Group struct {
	ID        int32
	Name      string
	CreatedAt time.Time
}

type Life struct {
	ID        int32
	Name      string
	GroupID   int32
	CreatedAt time.Time
}

type Member struct {
	ID        int32
	Name      string
	FirstName sql.NullString
	GroupID   int32
	Phase     int32
	Graduated bool
	CreatedAt time.Time
}

type Music struct {
	ID          int32
	Name        string
	Normal      int32
	Pro         int32
	Master      int32
	Length      int32
	ColorTypeID int32
	LiveID      int32
	ProPlus     int32
	MusicBonus  bool
	SetlistID   int32
	CreatedAt   time.Time
}

type Photograph struct {
	ID           int32
	Name         string
	GroupID      int32
	Abbreviation string
	Type         string
	CreatedAt    time.Time
}

type Producer struct {
	ID        int32
	CreatedAt time.Time
}

type ProducerScene struct {
	ID           int32
	ProducerID   int32
	PhotographID int32
	MemberID     int32
	Have         sql.NullBool
	CreatedAt    time.Time
}

type Scene struct {
	ID              int32
	PhotographID    int32
	MemberID        int32
	ColorTypeID     int32
	VocalMax        int32
	DanceMax        int32
	PeformanceMax   int32
	CenterSkillName sql.NullString
	ExpectedValue   sql.NullString
	SsrPlus         bool
	CreatedAt       time.Time
}

type Skill struct {
	ID                int32
	Name              string
	ComboUpPercent    sql.NullInt32
	DurationSec       sql.NullInt32
	ExpectedValue     float64
	IntervalSec       int32
	OccurrencePercent int32
	ScoreUpPercent    sql.NullInt32
	CreatedAt         time.Time
}
