// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: producer.sql

package repository

import (
	"context"
)

const getProducer = `-- name: GetProducer :one
SELECT
    id, provider_id, identity_id, is_admin, created_at
FROM
    producers p
WHERE
    p.identity_id = ?
`

func (q *Queries) GetProducer(ctx context.Context, db DBTX, identityID string) (Producer, error) {
	row := db.QueryRowContext(ctx, getProducer, identityID)
	var i Producer
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.IdentityID,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const getProducerWithAdmin = `-- name: GetProducerWithAdmin :one
SELECT
    id, provider_id, identity_id, is_admin, created_at
FROM
    producers p
WHERE
    p.identity_id = ? AND p.is_admin = 1
`

func (q *Queries) GetProducerWithAdmin(ctx context.Context, db DBTX, identityID string) (Producer, error) {
	row := db.QueryRowContext(ctx, getProducerWithAdmin, identityID)
	var i Producer
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.IdentityID,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const registProducer = `-- name: RegistProducer :exec
;

INSERT OR IGNORE INTO producers
    (provider_id, identity_id)
VALUES
    (?, ?)
`

type RegistProducerParams struct {
	ProviderID int64
	IdentityID string
}

func (q *Queries) RegistProducer(ctx context.Context, db DBTX, arg RegistProducerParams) error {
	_, err := db.ExecContext(ctx, registProducer, arg.ProviderID, arg.IdentityID)
	return err
}
