// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: producer_office.sql

package repository

import (
	"context"
	"database/sql"
)

const getProducerOffice = `-- name: GetProducerOffice :one
SELECT office_bonus FROM producer_offices WHERE id = 1
`

func (q *Queries) GetProducerOffice(ctx context.Context, db DBTX) (sql.NullInt64, error) {
	row := db.QueryRowContext(ctx, getProducerOffice)
	var office_bonus sql.NullInt64
	err := row.Scan(&office_bonus)
	return office_bonus, err
}

const updateProducerOffice = `-- name: UpdateProducerOffice :exec
UPDATE producer_offices SET office_bonus = ? WHERE id = 1
`

func (q *Queries) UpdateProducerOffice(ctx context.Context, db DBTX, officeBonus sql.NullInt64) error {
	_, err := db.ExecContext(ctx, updateProducerOffice, officeBonus)
	return err
}
