// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package repository

import (
	"context"
)

const getGroup = `-- name: GetGroup :many
SELECT id, name FROM ` + "`" + `groups` + "`" + `
`

func (q *Queries) GetGroup(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
