// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	GetCollections(ctx context.Context, db DBTX) ([]GetCollectionsRow, error)
	GetCollectionsWithColor(ctx context.Context, db DBTX, name string) ([]GetCollectionsWithColorRow, error)
	GetGroup(ctx context.Context, db DBTX) ([]GetGroupRow, error)
	GetMembers(ctx context.Context, db DBTX) ([]GetMembersRow, error)
	GetMusicList(ctx context.Context, db DBTX) ([]GetMusicListRow, error)
	GetMusicListWithColor(ctx context.Context, db DBTX, name string) ([]GetMusicListWithColorRow, error)
	GetScenes(ctx context.Context, db DBTX) ([]GetScenesRow, error)
	GetScenesWithColor(ctx context.Context, db DBTX, name string) ([]GetScenesWithColorRow, error)
	SeedCenterSkills(ctx context.Context, db DBTX) error
	SeedColorTypes(ctx context.Context, db DBTX) error
	SeedGroups(ctx context.Context, db DBTX) error
	SeedLives(ctx context.Context, db DBTX) error
	SeedMembers(ctx context.Context, db DBTX) error
	SeedMusic(ctx context.Context, db DBTX) error
	SeedPhotograph(ctx context.Context, db DBTX) error
	SeedScenes(ctx context.Context, db DBTX) error
	SeedSkills(ctx context.Context, db DBTX) error
}

var _ Querier = (*Queries)(nil)
