// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	GetCollections(ctx context.Context) ([]GetCollectionsRow, error)
	GetGroup(ctx context.Context) ([]Group, error)
	GetMembers(ctx context.Context) ([]GetMembersRow, error)
	GetMusicList(ctx context.Context) ([]GetMusicListRow, error)
	// WHERE
	// 	p.id = 1
	GetScenes(ctx context.Context) ([]GetScenesRow, error)
	SeedCenterSkills(ctx context.Context) error
	SeedColorTypes(ctx context.Context) error
	SeedGroups(ctx context.Context) error
	SeedLives(ctx context.Context) error
	SeedMembers(ctx context.Context) error
	SeedMusic(ctx context.Context) error
	SeedPhotograph(ctx context.Context) error
	SeedScenes(ctx context.Context) error
	SeedSkills(ctx context.Context) error
	SelectSceneList(ctx context.Context) ([]SelectSceneListRow, error)
}

var _ Querier = (*Queries)(nil)
