name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: go mod download

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

    - name: Generate sqlc code
      run: sqlc generate

    - name: Install gomock
      run: go install github.com/golang/mock/mockgen@latest

    - name: Generate mocks
      run: go generate ./...

    - name: Run tests
      run: go test -v -race -coverprofile=coverage.out ./...

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: go mod download

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

    - name: Generate sqlc code
      run: sqlc generate

    - name: Install gomock
      run: go install github.com/golang/mock/mockgen@latest

    - name: Generate mocks
      run: go generate ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=10m

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Download dependencies
      run: go mod download

    - name: Install sqlc
      run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

    - name: Generate sqlc code
      run: sqlc generate

    - name: Install gomock
      run: go install github.com/golang/mock/mockgen@latest

    - name: Generate mocks
      run: go generate ./...

    - name: Build
      run: go build -v ./...